defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"

# Site settings
name: Ruan C. Arcega
title: ruanc.dev
description: "DevOps Engineer"
url: "https://ruanc.dev"

# Delete the lines you don't need
# about 5 elements are recomended
github_username:  rca0
twitter_username: RuanArcega
linkedin_username: ruanc
email: me@ruanc.dev

avatar: yes
avatar_img_path: "https://github.com/rca0.png"

front_img: no
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Pages
blog_url: /blog.html

# Build settings
markdown: kramdown
permalink: pretty
